apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: prod

# Production-specific overrides
replicas:
  - name: url-shortener
    count: 5

patchesStrategicMerge:
  - deployment-prod.yaml
